const mongoose = require("mongoose");
const express = require("express");

const InquiryDetailSchema = new mongoose.Schema({
  id: { type: mongoose.Schema.Types.ObjectId },
  inquiry_id: { type: mongoose.Schema.Types.ObjectId },
  Ambient_Temp: { type: String },
  Anti_Collision: { type: String },
  capacity: { type: String },
  Span: { type: String },
  Height_of_lift: { type: String },
  Travel_Length: { type: String },
  Area_Classification: { type: String },
  Location: { type: String },
  Class: { type: String },
  Power_Supply: { type: String },
  Control_Voltage: { type: String },
  Crane_Quantity: { type: String },
  IS_Standard: { type: String },
  Operation: { type: String },
  Speeds_mpm: { type: String },
  Main_Micro_HOIST: { type: String },
  Main_Micro_C_T: { type: String },
  Main_Micro_L_T: { type: String },
  Hook_Type: { type: String },
  Main_Micro: { type: String },
  Motors: { type: String },
  H_P__K_W: { type: String },
  Motors_H_P__K_W_HOIST: { type: String },
  Motors_H_P__K_W_C_T: { type: String },
  Motors_H_P__K_W_L_T: { type: String },
  Motors_Make_HOIST: { type: String },
  Motors_Make_C_T: { type: String },
  Motors_Make_L_T: { type: String },
  Brake: { type: String },
  Brake_Type_HOIST: { type: String },
  Brake_Type_C_T: { type: String },
  Brake_Type_L_T: { type: String },
  Brake_Make_HOIST: { type: String },
  Brake_Make_C_T: { type: String },
  Brake_Make_L_T: { type: String },
  Limit_Switch_Type_HOIST: { type: String },
  Limit_Switch_Type_C_T: { type: String },
  Limit_Switch_Type_L_T: { type: String },
  Limit_Switch_Make_HOIST: { type: String },
  Limit_Switch_Make_C_T: { type: String },
  Limit_Switch_Make_L_T: { type: String },
  Wheel_HOIST: { type: String },
  Wheel_C_T: { type: String },
  Wheel_L_T: { type: String },
  Rail_Size_HOIST: { type: String },
  Rail_Size_C_T: { type: String },
  Rail_Size_L_T: { type: String },
  Type_of_Motion: { type: String },
  No_of_falls: { type: String },
  Wire_Rope_Size_Const: { type: String },
  Hook: { type: String },
  C_T_Power_Feeding: { type: String },
  L_T_Power_Feeding: { type: String },
  Buffer: { type: String },
  Platform: { type: String },
  Painting: { type: String },
  Hooter: { type: String },
  Bridge_Light: { type: String },
  Dsl_Maintenance_Cage: { type: String },
  Load_cell: { type: String },
  Jacking_Pad: { type: String },
  Crane_Weight: { type: String },
  Wheel_Load: { type: String },
  Brake_QTY_HOIST: { type: Number },
  Brake_QTY_C_T: { type: Number },
  Brake_QTY_L_T: { type: Number },
  Limit_Switch_QTY_HOIST: { type: Number },
  Limit_Switch_QTY_C_T: { type: Number },
  Limit_Switch_QTY_L_T: { type: Number },
  Wheel_QTY_HOIST: { type: Number },
  Wheel_QTY_C_T: { type: Number },
  Wheel_QTY_L_T: { type: Number },
  Motors_QTY_L_T: { type: String },
  Motors_QTY_C_T: { type: String },
  Motors_QTY_HOIST: { type: String },
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },

  //   inquiry_status: { type: String, required: true },
  //   inquiry_ID: { type: String, required: true },
  //   inquiryData: { type: String, require: true },
  //   quotationDate: { type: String },

  //   inq_number: { type: String },
  //   product_id: { type: String },
  //   customer_id: { type: String },
  //   customerFirstName: { type: String },
  //   customerPhone: { type: String },

  //   capacity: { type: String },
  //   Span: { type: String },
  //   Height_of_lift: { type: String },
  //   Travel_Length: { type: String },
  //   Area_Classification: { type: String },
  //   Location: { type: String },
  //   Ambient_Temp: { type: String },
  //   Class: { type: String },
  //   Power_Supply: { type: String },
  //   Control_Voltage: { type: String },
  //   Crane_Quantity: { type: String },
  //   IS_Standard: { type: String },
  //   Operation: { type: String },
  //   Speeds_mpm: { type: String },
  //   Main_Micro_HOIST: { type: String },
  //   Main_Micro_C_T: { type: String },
  //   Main_Micro_L_T: { type: String },
  //   Main_Micro: { type: String },
  //   Motors: { type: String },
  //   H_P__K_W: { type: String },

  //   Motors_H_P__K_W_HOIST: { type: String },
  //   Motors_H_P__K_W_C_T: { type: String },
  //   Motors_H_P__K_W_L_T: { type: String },
  //   Motors_Make_HOIST: { type: String },
  //   Motors_Make_C_T: { type: String },
  //   Motors_Make_L_T: { type: String },
  //   Motors_QTY_HOIST: { type: String },
  //   Motors_QTY_C_T: { type: String },
  //   Motors_QTY_L_T: { type: String },

  //   Break_Type_HOIST: { type: String },
  //   Break_Type_C_T: { type: String },
  //   Break_Type_L_T: { type: String },
  //   Break_Make_HOIST: { type: String },
  //   Break_Make_C_T: { type: String },
  //   Break_Make_L_T: { type: String },
  //   Break_QTY_HOIST: { type: String },
  //   Break_QTY_C_T: { type: String },
  //   Break_QTY_L_T: { type: String },

  //   Limit_Switch_Type_HOIST: { type: String },
  //   Limit_Switch_Type_C_T: { type: String },
  //   Limit_Switch_Type_L_T: { type: String },
  //   Limit_Switch_Make_HOIST: { type: String },
  //   Limit_Switch_Make_C_T: { type: String },
  //   Limit_Switch_Make_L_T: { type: String },
  //   Limit_Switch_QTY_HOIST: { type: String },
  //   Limit_Switch_QTY_C_T: { type: String },
  //   Limit_Switch_QTY_L_T: { type: String },

  //   Wheel_HOIST: { type: String },
  //   Wheel_C_T: { type: String },
  //   Wheel_L_T: { type: String },
  //   Wheel_QTY_HOIST: { type: String },
  //   Wheel_QTY_C_T: { type: String },
  //   Wheel_QTY_L_T: { type: String },

  //   Rail_Size_HOIST: { type: String },
  //   Rail_Size_C_T: { type: String },
  //   Rail_Size_L_T: { type: String },

  //   Motor_Make: { type: String },
  //   Motor_QTY: { type: String },
  //   Break: { type: String },
  //   Break_Type: { type: String },
  //   Break_Make: { type: String },
  //   Break_QTY: { type: String },
  //   Limit_Switch: { type: String },
  //   Limit_Switch_Type: { type: String },
  //   Limit_Switch_Make: { type: String },
  //   Limit_Switch_QTY: { type: String },
  //   Wheel: { type: String },
  //   Wheel_QTY: { type: String },
  //   Rail_Size: { type: String },
  //   Type_of_Motion: { type: String },
  //   No_of_Motion: { type: String },
  //   No_of_fails: { type: String },
  //   Wire_Rope_Size_Const: { type: String },
  //   Hook_Type: { type: String },
  //   Hook: { type: String },
  //   C_T_Power_Feeding: { type: String },
  //   L_T_Power_Feeding: { type: String },
  //   Buffer: { type: String },
  //   Platform: { type: String },
  //   Painting: { type: String },
  //   Hooter: { type: String },
  //   Anti_Collision: { type: String },
  //   Bridge_Light: { type: String },
  //   Dsl_Maintenance_Cage: { type: String },
  //   Load_cell: { type: String },
  //   Jacking_Pad: { type: String },
  //   Crane_Weight: { type: String },
  //   Wheel_Load: { type: String },
  //   CoverLetter: { type: String },
  //   TermAndCondition: { type: String },
  //   name: { type: String, required: true },
});

const InquiryDetailsModel = mongoose.model(
  "InquiryDetails",
  InquiryDetailSchema
);
module.exports = InquiryDetailsModel;
